import { DynamicPane }  from "../widgets/dynamic_pane.slint";
import { LeftTabEntry } from "../types.slint";

export component LeftPane inherits Rectangle {
    in-out property <[LeftTabEntry]> left-tabs;
    in-out property <int>   active-left-tab: 0;

    callback close-left-tab(int);
    callback move-left-tab(int, int);
    callback add-pane(int, int);
    callback tab-action-left(int, int);

    DynamicPane {
        width: 100%; height: 100%;
        tabs        <=> root.left-tabs;
        active-tab  <=> root.active-left-tab;
        current-area: 0;

        close-tab(i)       => { root.close-left-tab(i); }
        move-tab(i, t)     => { root.move-left-tab(i, t); }
        add-pane(a, t)     => { root.add-pane(a, t); }
        tab-action(i, a)   => { root.tab-action-left(i, a); }
    }
}
