export global Viewer3dGlobal {
    in property <image> teapot-image;
    callback viewer3d-panned(float, float);
    callback viewer3d-scrolled(float);
    callback viewer3d-resized(float, float);
}

export component PaneViewer3d inherits Rectangle {
    private property <float> drag-x;
    private property <float> drag-y;
    private property <float> cur-w: self.width / 1px;
    private property <float> cur-h: self.height / 1px;
    changed cur-w => { Viewer3dGlobal.viewer3d-resized(self.cur-w, self.cur-h); }
    changed cur-h => { Viewer3dGlobal.viewer3d-resized(self.cur-w, self.cur-h); }

    Image {
        source: Viewer3dGlobal.teapot-image;
        width: 100%; height: 100%;
        image-fit: fill;
    }
    TouchArea {
        mouse-cursor: crosshair;
        pointer-event(e) => {
            if (e.kind == PointerEventKind.down) {
                root.drag-x = self.mouse-x / 1px;
                root.drag-y = self.mouse-y / 1px;
            }
        }
        moved => {
            if (self.pressed) {
                Viewer3dGlobal.viewer3d-panned(
                    self.mouse-x / 1px - root.drag-x,
                    self.mouse-y / 1px - root.drag-y
                );
                root.drag-x = self.mouse-x / 1px;
                root.drag-y = self.mouse-y / 1px;
            }
        }
        scroll-event(e) => {
            Viewer3dGlobal.viewer3d-scrolled(e.delta-y / 1px);
            return EventResult.accept;
        }
    }
}
