export struct FileEntry {
    name: string,
    is-dir: bool,
    size: string,
}

export struct DevicePropEntry {
    device: string,
    property: string,
    value: string,
}

export struct TabMenuAction {
    label:     string,
    action-id: int,
}

export struct LeftTabEntry {
    label:        string,
    tab-type:     int,   // 0=3D View, 1=2D Viewer, 2=Camera
    menu-actions: [TabMenuAction],
}

export struct ProjectTreeEntry {
    label: string,
    indent: int,
    object-id: int,
    project-id: int,
}
